- name: Remove lxd snap
  become: true
  snap: name=lxd state=absent
  when: ansible_distribution_version is version('20.04', '==')
  ignore_errors: yes
- name: Remove core18 snap
  become: true
  snap: name=core18 state=absent
  when: ansible_distribution_version is version('20.04', '==')
  ignore_errors: yes
- name: Remove snapd snap
  become: true
  snap: name=snapd state=absent
  when: ansible_distribution_version is version('20.04', '==')
  ignore_errors: yes
- name: Remove amazon-ssm-agent
  become: true
  snap: name=amazon-ssm-agent state=absent
  when: ansible_distribution_version is version('20.04', '==')
  ignore_errors: yes
  register: snap_status

- name: Set fact for packages to remove (Ubuntu 20.04)
  become: true
  set_fact:
    ubuntu_annoying_packages:
      - whoopsie # security (CIS 4.1)
      - apport   # security (CIS 4.1)
      - command-not-found # annoying
      - command-not-found-data # annoying
      - python3-commandnotfound # annoying
      - snapd # annoying (Ubuntu >= 16.04)
      - lxd-agent-loader # annoying (Ubuntu 20.04)
- name: Remove packages
  become: true
  apt: name={{ ubuntu_annoying_packages }} state=absent purge=yes
- name: Disable marketing MOTD
  become: true
  file: path={{ item }} mode=0644 state=absent
  loop:
    - /etc/update-motd.d/99-esm # Ubuntu 14.04
    - /etc/update-motd.d/10-help-text # Ubuntu 14.04+
    - /etc/update-motd.d/50-motd-news # Ubuntu 18.04+
    - /etc/update-motd.d/80-esm # Ubuntu 18.04+
    - /etc/update-motd.d/80-livepatch # Ubuntu 18.04+
  ignore_errors: yes
- name: Disable marketing MOTD
  become: true
  systemd: name={{ item }} state=stopped enabled=no
  when: ansible_service_mgr == 'systemd'
  loop:
    - motd-news.service
    - motd-news.timer

- name: disable multipathd
  become: true
  service:
    name: multipathd
    state: stopped
    enabled: false

- name: reboot machine
  become: yes
  reboot:
  when: snap_status.changed
